/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.drone_highway.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class AirwayDetermination implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column airway_determination_id
     * @mbg.generated
     */
    private Integer airwayDeterminationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_number
     * @mbg.generated
     */
    private String businessNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fall_tolerance_range_id
     * @mbg.generated
     */
    private String fallToleranceRangeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column num_cross_section_divisions
     * @mbg.generated
     */
    private Integer numCrossSectionDivisions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column created_at
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column updated_at
     * @mbg.generated
     */
    private LocalDateTime updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column delete
     * @mbg.generated
     */
    private Boolean delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table airway_determination
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}
