/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.intent_exchange.drone_highway.api;

import javax.annotation.Generated;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.NoHandlerFoundException;
import com.intent_exchange.drone_highway.entity.FallToleranceRangeDeleteRequestEntity;
import com.intent_exchange.drone_highway.entity.FallToleranceRangeDetailGetRequestEntity;
import com.intent_exchange.drone_highway.entity.FallToleranceRangeDetailGetResponseEntity;
import com.intent_exchange.drone_highway.entity.FallToleranceRangeGetRequestEntity;
import com.intent_exchange.drone_highway.entity.FallToleranceRangeGetResponseEntity;
import com.intent_exchange.drone_highway.entity.FallToleranceRangePostRequestEntity;
import com.intent_exchange.drone_highway.entity.FallToleranceRangePostResponseEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2024-11-28T02:11:01.341514500Z[Etc/UTC]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "FallToleranceRange", description = "the FallToleranceRange API")
public interface FallToleranceRangeApi {

  /**
   * GET /fall-tolerance-range : 最大落下許容範囲取得 ドローン航路システムから、最大落下許容範囲情報を返却する。
   *
   * @param businessNumber 事業者番号 (required)
   * @return 正常終了 (status code 200) or パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。
   *         ・必須指定されているパラメータが指定されていない場合 ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 (status code 400)
   *         or サーバ内部にて主に以下に該当する問題が検知された場合に返却する。 ・他のサービスへのネットワークアクセスに失敗した ・サーバ内部でロジックの例外が検出された
   *         (status code 500)
   */
  @Operation(operationId = "fallToleranceRangeGet", summary = "最大落下許容範囲取得",
      description = "ドローン航路システムから、最大落下許容範囲情報を返却する。", tags = {"FallToleranceRange"},
      responses = {
          @ApiResponse(responseCode = "200", description = "正常終了",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = FallToleranceRangeGetResponseEntity.class))}),
          @ApiResponse(responseCode = "400",
              description = "パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。  ・必須指定されているパラメータが指定されていない場合  ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合   "),
          @ApiResponse(responseCode = "500",
              description = "サーバ内部にて主に以下に該当する問題が検知された場合に返却する。  ・他のサービスへのネットワークアクセスに失敗した  ・サーバ内部でロジックの例外が検出された ")})
  @RequestMapping(method = RequestMethod.GET, value = "/fall-tolerance-range",
      produces = {"application/json"})

  ResponseEntity<FallToleranceRangeGetResponseEntity> fallToleranceRangeGet(
      @Valid FallToleranceRangeGetRequestEntity fallToleranceRangeGetRequestEntity);


  /**
   * POST /fall-tolerance-range : 最大落下許容範囲登録 最大落下許容範囲をドローン航路システムに登録する。
   *
   * @param fallToleranceRangePostRequestEntity (required)
   * @return 正常終了 (status code 201) or パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。
   *         ・必須指定されているパラメータが指定されていない場合 ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 (status code 400)
   *         or サーバ内部にて主に以下に該当する問題が検知された場合に返却する。 ・他のサービスへのネットワークアクセスに失敗した ・サーバ内部でロジックの例外が検出された
   *         (status code 500)
   */
  @Operation(operationId = "fallToleranceRangePost", summary = "最大落下許容範囲登録",
      description = "最大落下許容範囲をドローン航路システムに登録する。", tags = {"FallToleranceRange"},
      responses = {
          @ApiResponse(responseCode = "201", description = "正常終了",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = FallToleranceRangePostResponseEntity.class))}),
          @ApiResponse(responseCode = "400",
              description = "パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。  ・必須指定されているパラメータが指定されていない場合  ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合   "),
          @ApiResponse(responseCode = "500",
              description = "サーバ内部にて主に以下に該当する問題が検知された場合に返却する。  ・他のサービスへのネットワークアクセスに失敗した  ・サーバ内部でロジックの例外が検出された ")})
  @RequestMapping(method = RequestMethod.POST, value = "/fall-tolerance-range",
      produces = {"application/json"}, consumes = {"application/json"})

  ResponseEntity<FallToleranceRangePostResponseEntity> fallToleranceRangePost(@Parameter(
      name = "FallToleranceRangePostRequestEntity", description = "",
      required = true) @Valid @RequestBody FallToleranceRangePostRequestEntity fallToleranceRangePostRequestEntity);


  /**
   * DELETE /fall-tolerance-range : 最大落下許容範囲削除 ドローン航路システムから、最大落下許容範囲情報を削除する。
   * 最大落下許容範囲が既に航路画定で使用されてる場合は、削除は出来ないものとする。
   *
   * @param fallToleranceRangeId 最大落下許容範囲ID (required)
   * @param businessNumber 事業者番号 (required)
   * @return 正常終了 (status code 204) or パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。
   *         ・必須指定されているパラメータが指定されていない場合 ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 (status code 400)
   *         or 指定された事業者番号,最大落下許容範囲IDが、データベースに存在しない場合に返却する。 (status code 404) or
   *         最大落下許容範囲が航路画定に使用されている場合に返却する。 (status code 409) or サーバ内部にて主に以下に該当する問題が検知された場合に返却する。
   *         ・他のサービスへのネットワークアクセスに失敗した ・サーバ内部でロジックの例外が検出された (status code 500)
   */
  @Operation(operationId = "fallToleranceRangeDelete", summary = "最大落下許容範囲削除",
      description = "ドローン航路システムから、最大落下許容範囲情報を削除する。  最大落下許容範囲が既に航路画定で使用されてる場合は、削除は出来ないものとする。 ",
      tags = {"FallToleranceRange"},
      responses = {@ApiResponse(responseCode = "204", description = "正常終了"), @ApiResponse(
          responseCode = "400",
          description = "パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。  ・必須指定されているパラメータが指定されていない場合  ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 "),
          @ApiResponse(responseCode = "404",
              description = "指定された事業者番号,最大落下許容範囲IDが、データベースに存在しない場合に返却する。 "),
          @ApiResponse(responseCode = "409", description = "最大落下許容範囲が航路画定に使用されている場合に返却する。 "),
          @ApiResponse(responseCode = "500",
              description = "サーバ内部にて主に以下に該当する問題が検知された場合に返却する。  ・他のサービスへのネットワークアクセスに失敗した  ・サーバ内部でロジックの例外が検出された ")})
  @RequestMapping(method = RequestMethod.DELETE, value = "/fall-tolerance-range")

  ResponseEntity<Void> fallToleranceRangeDelete(
      @Valid FallToleranceRangeDeleteRequestEntity fallToleranceRangeDeleteRequestEntity)
      throws NoHandlerFoundException;

  /**
   * GET /fall-tolerance-range/{fallToleranceRangeId}/{businessNumber} : 最大落下許容範囲情報の取得
   * ドローン航路システムから、指定された最大落下許容範囲ID,事業者番号をキーにした最大落下許容範囲情報を取得する。
   *
   * @param fallToleranceRangeId 最大落下許容範囲ID (required)
   * @param businessNumber 事業者番号 (required)
   * @return 正常終了 (status code 200) or パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。
   *         ・必須指定されているパラメータが指定されていない場合 ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 (status code 400)
   *         or 指定された事業者番号,最大落下許容範囲IDが、データベースに存在しない場合に返却する。 (status code 404) or
   *         サーバ内部にて主に以下に該当する問題が検知された場合に返却する。 ・他のサービスへのネットワークアクセスに失敗した ・サーバ内部でロジックの例外が検出された (status
   *         code 500)
   */
  @Operation(operationId = "fallToleranceRangeDetailGet", summary = "最大落下許容範囲情報の取得",
      description = "ドローン航路システムから、指定された最大落下許容範囲ID,事業者番号をキーにした最大落下許容範囲情報を取得する。",
      tags = {"FallToleranceRange"},
      responses = {
          @ApiResponse(responseCode = "200", description = "正常終了",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(
                      implementation = FallToleranceRangeDetailGetResponseEntity.class))}),
          @ApiResponse(responseCode = "400",
              description = "パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。  ・必須指定されているパラメータが指定されていない場合  ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 "),
          @ApiResponse(responseCode = "404",
              description = "指定された事業者番号,最大落下許容範囲IDが、データベースに存在しない場合に返却する。 "),
          @ApiResponse(responseCode = "500",
              description = "サーバ内部にて主に以下に該当する問題が検知された場合に返却する。  ・他のサービスへのネットワークアクセスに失敗した  ・サーバ内部でロジックの例外が検出された ")})
  @RequestMapping(method = RequestMethod.GET,
      value = "/fall-tolerance-range/{fallToleranceRangeId}/{businessNumber}",
      produces = {"application/json"})

  ResponseEntity<FallToleranceRangeDetailGetResponseEntity> fallToleranceRangeDetailGet(
      @Valid FallToleranceRangeDetailGetRequestEntity fallToleranceRangeDetailGetRequestEntity)
      throws NoHandlerFoundException;

}

