/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.intent_exchange.drone_highway.api;

import javax.annotation.Generated;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.NoHandlerFoundException;
import com.intent_exchange.drone_highway.entity.FallSpaceCrossSectionPostRequestEntity;
import com.intent_exchange.drone_highway.entity.FallSpaceCrossSectionPostResponseEntity;
import com.intent_exchange.drone_highway.entity.FallSpacePostRequestEntity;
import com.intent_exchange.drone_highway.entity.FallSpacePostResponseEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2024-12-16T04:57:50.352694600Z[Etc/UTC]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "FallSpace", description = "the FallSpace API")
public interface FallSpaceApi {

  /**
   * POST /fall-space-cross-section : 落下空間(断面)取得
   * ドローン航路システムから、指定された落下範囲節を元に落下空間断面の上部の座標リストを返却する。
   *
   * @param fallSpaceCrossSectionPostRequestEntity (required)
   * @return 正常終了 (status code 200) or パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。
   *         ・必須指定されているパラメータが指定されていない場合 ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 (status code 400)
   *         or 指定された航路画定IDが、データベースに存在しない場合に返却する。 (status code 404) or
   *         サーバ内部にて主に以下に該当する問題が検知された場合に返却する。 ・他のサービスへのネットワークアクセスに失敗した ・サーバ内部でロジックの例外が検出された (status
   *         code 500)
   */
  @Operation(operationId = "fallSpaceCrossSectionPost", summary = "落下空間(断面)取得",
      description = "ドローン航路システムから、指定された落下範囲節を元に落下空間断面の上部の座標リストを返却する。", tags = {"FallSpace"},
      responses = {
          @ApiResponse(responseCode = "200", description = "正常終了",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(
                      implementation = FallSpaceCrossSectionPostResponseEntity.class))}),
          @ApiResponse(responseCode = "400",
              description = "パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。  ・必須指定されているパラメータが指定されていない場合  ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合   "),
          @ApiResponse(responseCode = "404", description = "指定された航路画定IDが、データベースに存在しない場合に返却する。 "),
          @ApiResponse(responseCode = "500",
              description = "サーバ内部にて主に以下に該当する問題が検知された場合に返却する。  ・他のサービスへのネットワークアクセスに失敗した  ・サーバ内部でロジックの例外が検出された ")})
  @RequestMapping(method = RequestMethod.POST, value = "/fall-space-cross-section",
      produces = {"application/json"}, consumes = {"application/json"})

  ResponseEntity<FallSpaceCrossSectionPostResponseEntity> fallSpaceCrossSectionPost(@Parameter(
      name = "FallSpaceCrossSectionPostRequestEntity", description = "",
      required = true) @Valid @RequestBody FallSpaceCrossSectionPostRequestEntity fallSpaceCrossSectionPostRequestEntity)
      throws NoHandlerFoundException;


  /**
   * POST /fall-space : 落下空間取得 指定された最大落下許容範囲ID,
   * 機体グループリストを元にデジタル地上リスク評価サービスから落下空間を取得し、ドローン航路システムに落下空間を登録する。 作成中の航路を一意に表す航路画定のIDを返却する。
   *
   * @param fallSpacePostRequestEntity (required)
   * @return 正常終了 (status code 201) or パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。
   *         ・必須指定されているパラメータが指定されていない場合 ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合 (status code 400)
   *         or 指定された最大落下許容範囲IDが、データベースに存在しない場合に返却する。 (status code 404) or
   *         サーバ内部にて主に以下に該当する問題が検知された場合に返却する。 ・他のサービスへのネットワークアクセスに失敗した ・サーバ内部でロジックの例外が検出された (status
   *         code 500)
   */
  @Operation(operationId = "fallSpacePost", summary = "落下空間取得",
      description = "指定された最大落下許容範囲ID, 機体グループリストを元にデジタル地上リスク評価サービスから落下空間を取得し、ドローン航路システムに落下空間を登録する。  作成中の航路を一意に表す航路画定のIDを返却する。 ",
      tags = {"FallSpace"},
      responses = {
          @ApiResponse(responseCode = "201", description = "正常終了",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = FallSpacePostResponseEntity.class))}),
          @ApiResponse(responseCode = "400",
              description = "パラメータに誤りがある場合に返却する。具体的には以下のケースを想定する。  ・必須指定されているパラメータが指定されていない場合  ・指定されたパラメータにバイト数の上限があり且つ、最大バイトサイズが上限を超えた場合   "),
          @ApiResponse(responseCode = "404",
              description = "指定された最大落下許容範囲IDが、データベースに存在しない場合に返却する。 "),
          @ApiResponse(responseCode = "500",
              description = "サーバ内部にて主に以下に該当する問題が検知された場合に返却する。  ・他のサービスへのネットワークアクセスに失敗した  ・サーバ内部でロジックの例外が検出された ")})
  @RequestMapping(method = RequestMethod.POST, value = "/fall-space",
      produces = {"application/json"}, consumes = {"application/json"})

  ResponseEntity<FallSpacePostResponseEntity> fallSpacePost(@Parameter(
      name = "FallSpacePostRequestEntity", description = "",
      required = true) @Valid @RequestBody FallSpacePostRequestEntity fallSpacePostRequestEntity)
      throws NoHandlerFoundException;

}

