/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.drone_highway.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import com.intent_exchange.drone_highway.model.AirwayDetermination;

@Mapper
@Repository
public interface AirwayDeterminationMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * airway_determination
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(Integer airwayDeterminationId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * airway_determination
   *
   * @mbg.generated
   */
  int insert(AirwayDetermination row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * airway_determination
   *
   * @mbg.generated
   */
  int insertSelective(AirwayDetermination row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * airway_determination
   *
   * @mbg.generated
   */
  AirwayDetermination selectByPrimaryKey(Integer airwayDeterminationId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * airway_determination
   *
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(AirwayDetermination row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * airway_determination
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(AirwayDetermination row);

  /**
   * 最大落下許容範囲IDを指定して行ロックを行った航路画定を取得する
   * 
   * @param fallToleranceRangeId 最大落下許容範囲ID
   * @return 航路画定
   */
  List<AirwayDetermination> selectLockByFallToleranceRangeId(String fallToleranceRangeId);

  /**
   * 航路IDを指定して行ロックを行った航路画定を取得する
   * 
   * @param airwayDeterminationId 航路確定ID
   * @return 航路確定
   */
  AirwayDetermination selectLockByPrimaryKey(Integer airwayDeterminationId);

}

