/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.drone_highway.dao;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import com.intent_exchange.drone_highway.model.FallToleranceRange;
import com.intent_exchange.drone_highway.model.FallToleranceRangeAirwayIdUse;

@Mapper
@Repository
public interface FallToleranceRangeMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fall_tolerance_range
   *
   * @mbg.generated
   */
  FallToleranceRange selectByPrimaryKey(String fallToleranceRangeId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fall_tolerance_range
   *
   * @mbg.generated
   */
  int insert(FallToleranceRange row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * fall_tolerance_range
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(FallToleranceRange row);

  /**
   * 引数に関連する最大落下許容範囲を取得する
   * 
   * @param conditions 条件
   * @return 最大落下許容範囲
   */
  List<FallToleranceRangeAirwayIdUse> selectByConditions(FallToleranceRange conditions);

  /**
   * 引数に関連する航路運営者IDを取得する<br>
   * 航路運営者IDと事業者番号は1:1の関係を前提とする
   * 
   * @param businessNumber 事業者番号
   * @return 航路運営者ID
   */
  String selectForOperatorId(String businessNumber);

  /**
   * 最大落下許容範囲IDを指定して行ロックを行った最大落下許容範囲を取得する
   * 
   * @param fallToleranceRangeId 最大落下許容範囲ID
   * @return 最大落下許容範囲
   */
  FallToleranceRange selectLockByPrimaryKey(String fallToleranceRangeId);

}

